Update with Drush 9 support.
DoghouseMedia/drupal-phing-build pull request #1
Opened 2018-09-19 01:07 UTC by inuk66

2018-09-19 01:10 UTC, rob3000 requested changes

2018-09-19 01:10 UTC, rob3000 commented on composer.json
> +        "jorgegc/phing-drush": "~4.2",
There should be a `composer.lock` update as well https://github.com/DoghouseMedia/drupal-phing-build/blob/master/composer.lock#L394

2018-09-21 01:25 UTC, inuk66 commented on composer.json
> +        "jorgegc/phing-drush": "~4.2",
Done :)

2018-09-21 01:53 UTC, rob3000 approved these changes

2018-09-21 01:53 UTC, merged